CREATE DATABASE MATEMAGIKA;

USE MATEMAGIKA;

CREATE TABLE USERS(
	IDUSER INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(30) NOT NULL,
	SCHOOLING VARCHAR(50),
	UF CHAR(2),
	BIRTH DATE,
	CREATION DATE,
	BALANCE INT,
	EXP INT,
	ADM BIT,
	ID_LEVEL INT
);

CREATE TABLE ITEMS(
	IDITEM INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30),
	NAMECOMPLEMENT VARCHAR(50),
	PRICE INT,
	RARITY VARCHAR(20),
	TYPE VARCHAR(20),
	LEVELREQUIRED INT,
	SOURCE VARCHAR(50)
);

INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Matemago', '<i class="fa-solid fa-wand-magic-sparkles"></i>', 0, 'common', 'mage', 1, 'matemago.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Matemaga', '🌺', 100, 'common', 'mage', 1, 'matemaga.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Agromago', '<i class="fa-solid fa-wheat-awn">', 200, 'rare', 'mage', 1, 'agromago.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Matemamago', '🐒', 600, 'epic', 'mage', 5, 'matemamago.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Magonha', '<i class="fa-solid fa-cannabis"></i>', 4200, 'legendary', 'mage', 10, 'magonha.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Padrão', NULL, 0, 'common', 'background', 1, 'default-background.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Arco-íris', NULL, 100, 'rare', 'background', 2, 'rainbow-background.png');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Light Weight', NULL, 2300, 'legendary', 'background', 8, 'light-weight-background.jpeg');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Céu', NULL, 300, 'rare', 'background', 3, 'sky-background.jpg');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Lua', NULL, 600, 'epic', 'background', 6, 'moon-background.jpg');
INSERT INTO ITEMS(NAME, NAMECOMPLEMENT, PRICE, RARITY, TYPE, LEVELREQUIRED, SOURCE) VALUES('Copa do Mundo', NULL, 800, 'epic', 'background', , 'worldcup-background.jpg');

CREATE TABLE ITEMS_OWNED(
	ID_USER INT,
	ID_ITEM INT
);

ALTER TABLE ITEMS_OWNED ADD CONSTRAINT FK_ITEMS_OWNED__USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);

ALTER TABLE ITEMS_OWNED ADD CONSTRAINT FK_ITEMS_OWNED__ITEMS
FOREIGN KEY (ID_ITEM) REFERENCES ITEMS(IDITEM);

CREATE TABLE ITEMS_SELECTED(
	TYPE VARCHAR(20),
	ID_USER INT,
	ID_ITEM INT
);

ALTER TABLE ITEMS_SELECTED ADD CONSTRAINT FK_ITEMS_SELECTED__USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);

ALTER TABLE ITEMS_SELECTED ADD CONSTRAINT FK_ITEMS_SELECTED__ITEMS
FOREIGN KEY (ID_ITEM) REFERENCES ITEMS(IDITEM);

CREATE TABLE CONTENTS(
	IDCONTENT INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50)UNIQUE,
	CTEXT TEXT, 
	ID_CATEGORY INT
);

CREATE TABLE EXAMS(
	IDEXAM INT PRIMARY KEY AUTO_INCREMENT,
	ID_CONTENT INT
);

CREATE TABLE CATEGORIES(
	IDCATEGORY INT PRIMARY KEY,
	NAME VARCHAR(30),
	EXP INT,
	COINS INT
);

ALTER TABLE CONTENTS ADD CONSTRAINT FK_CONTENTS_CATEGORIES
FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES(IDCATEGORY);

ALTER TABLE EXAMS ADD CONSTRAINT FK_EXAMS_CONTENTS
FOREIGN KEY (ID_CONTENT) REFERENCES CONTENTS(IDCONTENT);

INSERT INTO CATEGORIES VALUES(1, '1fundamental', 10, 5);
INSERT INTO CATEGORIES VALUES(2, '2fundamental', 20, 10);
INSERT INTO CATEGORIES VALUES(3, 'high-school', 40, 15);

INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Soma', 'para somar some os dois números',1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Diferença', 'para subtrair subtraia os dois números', 1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Multiplicação', 'para multiplicar multiplique os dois números', 1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Divisão', 'para dividir divida os dois números', 1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Expressões Simples', 'para realziar a expressão comece realizando ela', 1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Formas', 'para diferenciar as formas comece abrindo o olho', 1);
INSERT INTO CONTENTS(NAME, CTEXT, ID_CATEGORY) VALUES('Função de segundo grau', 'para realizar uma função de segundo grau comece aprendendo bhaskara (imagem)https://www.dicasdecalculo.com.br/wp-content/uploads/2017/05/Fun%C3%A7%C3%A3o-do-2-grau.jpg(_imagem) e depois vá na fé se não for ateu', 3);

INSERT INTO users(NAME, EMAIL, PASSWORD, SCHOOLING, UF, BIRTH, CREATION, BALANCE, EXP, ID_LEVEL, TEACHER) VALUES ('adm', 'adm@gmail.com', '12345678', 'Ensino superior completo', 'PR', '2022-10-20', '2022-10-12', 0, 900, 5, 1);

CREATE TABLE EXAMS_PERFORMED(
	ID_USER INT,
	ID_EXAM INT
);

ALTER TABLE EXAMS_PERFORMED ADD CONSTRAINT FK_EXAMS_PERFORMED__USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);

ALTER TABLE EXAMS_PERFORMED ADD CONSTRAINT FK_EXAMS_PERFORMED__EXAMS
FOREIGN KEY (ID_EXAM) REFERENCES EXAMS(IDEXAM);


CREATE TABLE CONTENTS_COMPLETED(
	ID_USER INT,
	ID_CONTENT INT
);

ALTER TABLE CONTENTS_SEEN ADD CONSTRAINT FK_CONTENTS_SEEN__USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);

ALTER TABLE CONTENTS_SEEN ADD CONSTRAINT FK_CONTENTS_SEEN__EXAMS
FOREIGN KEY (ID_CONTENT) REFERENCES EXAMS(IDCONTENT);

CREATE TABLE QUESTIONS(
	IDQUESTION INT PRIMARY KEY AUTO_INCREMENT,
	QTEXT TEXT UNIQUE,
	ALTERNATIVE1 TEXT,
	ALTERNATIVE2 TEXT,
	ALTERNATIVE3 TEXT,
	ALTERNATIVE4 TEXT,
	ALTERNATIVE5 TEXT,
	CORRECT INT
);

CREATE TABLE EXAMS_QUESTIONS(
	ID_EXAM INT,
	ID_QUESTION INT
);
	
ALTER TABLE EXAMS_QUESTIONS ADD CONSTRAINT FK_EXAMS_QUESTIONS__EXAMS
FOREIGN KEY (ID_EXAM) REFERENCES EXAMS(IDEXAM);

ALTER TABLE EXAMS_QUESTIONS ADD CONSTRAINT FK_EXAMS_QUESTIONS__QUESTIONS
FOREIGN KEY (ID_QUESTION) REFERENCES QUESTIONS(IDQUESTION);

CREATE TABLE CONTENTS_QUESTIONS(
	ID_CONTENT INT,
	ID_QUESTION INT
);

ALTER TABLE CONTENTS_QUESTIONS ADD CONSTRAINT FK_CONTENTS_QUESTIONS__CONTENTS
FOREIGN KEY (ID_CONTENT) REFERENCES CONTENTS(IDCONTENT);

ALTER TABLE CONTENTS_QUESTIONS ADD CONSTRAINT FK_CONTENTS_QUESTIONS__QUESTIONS
FOREIGN KEY (ID_QUESTION) REFERENCES QUESTIONS(IDQUESTION);

CREATE TABLE QUESTIONS_ANSWERED(
	ID_USER INT,
	ID_QUESTION INT
);

ALTER TABLE QUESTIONS_ANSWERED ADD CONSTRAINT FK_QUESTIONS_ANSWERED__USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);

ALTER TABLE QUESTIONS_ANSWERED ADD CONSTRAINT FK_QUESTIONS_ANSWERED__QUESTIONS
FOREIGN KEY (ID_QUESTION) REFERENCES QUESTIONS(IDQUESTION);

CREATE TABLE LEVELS(
	IDLEVEL INT PRIMARY KEY,
	MINEXP INT,
	MAXEXP INT
);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_LEVELS
FOREIGN KEY (ID_LEVEL) REFERENCES LEVELS(IDLEVEL);

INSERT INTO LEVELS VALUES(1, 0, 99);
INSERT INTO LEVELS VALUES(2, 100, 249);
INSERT INTO LEVELS VALUES(3, 250, 449);
INSERT INTO LEVELS VALUES(4, 450, 699);
INSERT INTO LEVELS VALUES(5, 700, 999);
INSERT INTO LEVELS VALUES(6, 1000, 1349);
INSERT INTO LEVELS VALUES(7, 1350, 1749);
INSERT INTO LEVELS VALUES(8, 1750, 2199);
INSERT INTO LEVELS VALUES(9, 2200, 2699);
INSERT INTO LEVELS VALUES(10, 2700, 3299);
INSERT INTO LEVELS VALUES(11, 3300, 3999);
INSERT INTO LEVELS VALUES(12, 4000, 4799);
INSERT INTO LEVELS VALUES(13, 4800, 5699);
INSERT INTO LEVELS VALUES(14, 5700, 6699);
INSERT INTO LEVELS VALUES(15, 6700, 7849);
INSERT INTO LEVELS VALUES(16, 7850, 9149);
INSERT INTO LEVELS VALUES(17, 9150, 10599);
INSERT INTO LEVELS VALUES(18, 10600, 12199);
INSERT INTO LEVELS VALUES(19, 12200, 13999);
INSERT INTO LEVELS VALUES(20, 14000, 1000013999);

CREATE TABLE DAILYGAMES(
	IDDAILYGAME INT PRIMARY KEY AUTO_INCREMENT,
	PLAYEDDATE DATE,
	RESULT INT,
	ID_USER INT
);

ALTER TABLE DAILYGAMES ADD CONSTRAINT FK_DAILYGAMES_USERS
FOREIGN KEY (ID_USER) REFERENCES USERS(IDUSER);